name: Compile
run-name: Check compilation

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  compilation:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name : Compile
      run: make
