name: Format
run-name: Code formating

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install clang-format

    - name: Format source files
      run: make clang-format

    - name : Compile
      run: make

    - name: Create new branch
      run: |
        git checkout -b formatted-main
  
    - name: Add Commit Push
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: .
        message: "Commit from GitHub Actions (Format)"
        push: origin formatted-main
        github_token: ${{ secrets.ACTIONS_PAT }}
