name: Format
run-name: Code formating

on:
  pull_request:
    branches:
      - 'clang-formating'
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install clang-format

    - name: Format source files
      run: make clang-format

    - name : Compile
      run: make

    - name: Create new branch
      run: |
        git checkout -b formatted-${{ github.event.pull_request.head.ref}}
  
    - name: Add Commit Push
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: .
        message: "Commit from GitHub Actions (Format)"
        push: origin formatted-${{ github.event.pull_request.head.ref }}
        github_token: ${{ secrets.ACTIONS_PAT }}
