name: Format
run-name: Code formating

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install clang-format

    - name: Check formatting
      run: make check-format
